name: test-ci-cd
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.1"

      - name: install dependencies
        run: pip install requests flask pytest

      - name: run and test unit test
        run: |
          if pytest -q unit_test.py; then
            echo "unit test success";
          else
            echo "unit test fails"
            exit 1
          fi
          
    
