name: test-ci-cd

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install dependencies
        run: pip install flask requests pytest

      - name: test and report unit test
        run: |
          if pytest -q "unit_test.py"; then
            echo "unit test success";
          else
            echo "unit test fail"
            exit 1
          fi 
            
